-- AlterTable
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "pricepernight" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Room" ADD COLUMN IF NOT EXISTS "monthlyrent" DOUBLE PRECISION NOT NULL DEFAULT 0;

