export const EXPENSE_CATEGORIES = [
    {
        key: 'MESS',
        label: 'Mess',
        slug: 'mess',
        icon: '🍽️',
        description: 'Daily meals, groceries & kitchen supplies',
        color: 'bg-orange-500',
        light: 'bg-orange-50',
        text: 'text-orange-700',
        border: 'border-orange-200',
        gradient: 'from-orange-500 to-orange-600',
        shadow: 'shadow-orange-100',
    },
    {
        key: 'GENERAL',
        label: 'General',
        slug: 'general',
        icon: '📋',
        description: 'Miscellaneous operational expenses',
        color: 'bg-slate-500',
        light: 'bg-slate-50',
        text: 'text-slate-700',
        border: 'border-slate-200',
        gradient: 'from-slate-500 to-slate-600',
        shadow: 'shadow-slate-100',
    },
    {
        key: 'UTILITY_BILL',
        label: 'Utility Bill',
        slug: 'utility-bill',
        icon: '⚡',
        description: 'Electricity, gas, water & internet bills',
        color: 'bg-blue-500',
        light: 'bg-blue-50',
        text: 'text-blue-700',
        border: 'border-blue-200',
        gradient: 'from-blue-500 to-blue-600',
        shadow: 'shadow-blue-100',
    },
    {
        key: 'MAINTENANCE',
        label: 'Maintenance',
        slug: 'maintenance',
        icon: '🔧',
        description: 'Repairs, upkeep & infrastructure work',
        color: 'bg-amber-500',
        light: 'bg-amber-50',
        text: 'text-amber-700',
        border: 'border-amber-200',
        gradient: 'from-amber-500 to-amber-600',
        shadow: 'shadow-amber-100',
    },
    {
        key: 'SALARY',
        label: 'Salary',
        slug: 'salary',
        icon: '💼',
        description: 'Staff wages, bonuses & disbursements',
        color: 'bg-purple-500',
        light: 'bg-purple-50',
        text: 'text-purple-700',
        border: 'border-purple-200',
        gradient: 'from-purple-500 to-purple-600',
        shadow: 'shadow-purple-100',
    },
];
